--
-- PostgreSQL database dump
--

\restrict WLIuz7nOjQvB2GoX4X4rQBO9V128lRSKLVQijrYwQp93law4hm11WKssqJWYx9e

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cities" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "Rating" double precision NOT NULL,
    "Population" integer NOT NULL,
    "Tags" text DEFAULT ''::text NOT NULL,
    "SearchQuery" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Cities" OWNER TO postgres;

--
-- Name: Cities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Name" text NOT NULL,
    "HomeCity" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Cities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Cities" ("Id", "Name", "Description", "ImageUrl", "Rating", "Population", "Tags", "SearchQuery") FROM stdin;
26	Санкт-Петербург	Культурная столица с белыми ночами, дворцами и каналами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/saint_petersburg_1.jpg	4.9	5000000	история,музеи,архитектура,еда	Saint Petersburg Russia palace
34	Суздаль	Открытый музей под небом — древний город с 53 церквями и медовухой	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/suzdal_1.jpg	4.9	10000	история,религия,архитектура	Suzdal Russia golden ring
116	Хабаровск	Амурский город с набережной и тигром на гербе у границы с Китаем	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/khabarovsk_1.jpg	4.4	610000	история,природа,культура	Khabarovsk Russia Amur river
22	Москва	Столица России — город контрастов, где древние соборы соседствуют с небоскрёбами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/moscow_1.jpg	4.9	12000000	история,архитектура,еда,ночная жизнь	Moscow Russia Red Square
112	Пермь	Культурная столица Урала с балетом и пермским звериным стилем	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/perm_1.jpg	4.4	1050000	культура,история,природа	Perm Russia Ural culture ballet
32	Шуя	Уютный купеческий городок с высокой колокольней и тихими улочками	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/shuya_1.jpg	4.2	55000	история,архитектура,природа	Shuya Russia historic town
67	Екатеринбург	Столица Урала — место расстрела царской семьи и ворота в Азию	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/yekaterinburg_1.jpg	4.6	1500000	история,архитектура,культура	Yekaterinburg Russia Ural city
77	Краснодар	Южная столица с платановыми аллеями, казачьей историей и вкусной едой	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/krasnodar_1.jpg	4.5	900000	история,еда,культура	Krasnodar Russia southern city
72	Красноярск	Город у Енисея с заповедником Столбы и великолепной сибирской природой	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/krasnoyarsk_1.jpg	4.6	1100000	природа,активный,культура	Krasnoyarsk Russia Yenisei Stolby
106	Липецк	Металлургический город с курортом и запасами целебной воды	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/lipetsk_1.jpg	4.1	500000	история,здоровье,природа	Lipetsk Russia resort city
70	Новосибирск	Столица Сибири с оперным театром и Академгородком	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/novosibirsk_1.jpg	4.4	1600000	культура,наука,архитектура	Novosibirsk Russia Siberia opera
71	Омск	Сибирский город с достоевским прошлым и красивой набережной Иртыша	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/omsk_1.jpg	4.2	1100000	история,культура,природа	Omsk Russia Irtysh river
94	Петрозаводск	Столица Карелии у Онежского озера — ворота к водопаду Кивач	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/petrozavodsk_1.jpg	4.4	270000	природа,культура,история	Petrozavodsk Karelia Russia lake
93	Псков	Древний форпост с мощным кремлём-детинцем на слиянии рек	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/pskov_1.jpg	4.6	210000	история,архитектура,природа	Pskov Russia kremlin ancient
61	Самара	Волжский город с бункером Сталина, набережной и знаменитым пивом	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/samara_1.jpg	4.5	1200000	история,природа,еда	Samara Russia Volga embankment
62	Саратов	Город с консерваторией, набережной и родиной Гагарина рядом	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/saratov_1.jpg	4.3	840000	история,культура,природа	Saratov Russia Volga city
109	Смоленск	Крепость-страж на западных рубежах с мощными стенами XVII века	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/smolensk_1.jpg	4.5	330000	история,архитектура,природа	Smolensk Russia fortress ancient
107	Тамбов	Тихий город тамбовского волка с усадьбами и старинными церквями	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/tambov_1.jpg	4	280000	история,природа,культура	Tambov Russia provincial city
100	Тула	Город пряников, самоваров и оружейных мастеров	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/tula_1.jpg	4.5	470000	история,еда,культура	Tula Russia kremlin gingerbread samovar
75	Чита	Забайкальский город — родина декабристов на пути к Байкалу	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/chita_1.jpg	4.1	340000	история,природа,культура	Chita Russia Transbaikalia
53	Ярославль	Первый город Золотого кольца с набережной Волги и старинными церквями	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/yaroslavl_1.jpg	4.7	600000	история,архитектура,природа	Yaroslavl Russia Volga cathedral
140	Ялта	Жемчужина Крыма — курортный город на берегу Чёрного моря с дворцами и набережной	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/yalta_1.jpg	4.8	76746	море,история,архитектура	Ялта Крым курорт
141	Севастополь	Город русской славы с бухтами, историческими укреплениями и чистым морем	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/sevastopol_1.jpg	4.7	509992	море,история,архитектура	Севастополь Крым флот
142	Бахчисарай	Бывшая столица Крымского ханства с ханским дворцом и пещерными городами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/bakhchisaray_1.jpg	4.6	26361	история,архитектура,природа	Бахчисарай дворец пещеры
143	Судак	Город с величественной Генуэзской крепостью и лучшими пляжами Крыма	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/sudak_1.jpg	4.6	16000	море,история,природа	Судак крепость пляж
73	Иркутск	Ворота к Байкалу с деревянными особняками и сибирским духом	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/irkutsk_1.jpg	4.7	620000	история,природа,архитектура	Irkutsk Russia Baikal gateway
144	Пятигорск	Курортный город у подножия горы Машук с минеральными источниками и видами на Кавказ	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/pyatigorsk_1.jpg	4.5	145871	природа,история,курорт	Пятигорск КМВ Лермонтов
145	Кисловодск	Самый солнечный курорт России с нарзаном и знаменитым курортным парком	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/kislovodsk_1.jpg	4.7	128442	природа,курорт,парк	Кисловодск нарзан парк
146	Дербент	Древнейший город России с крепостью Нарын-Кала и уникальной многовековой историей	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/derbent_1.jpg	4.6	126895	история,архитектура,культура	Дербент крепость Дагестан
147	Кострома	Родина Снегурочки и центр ювелирного дела на берегу Волги	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/kostroma_1.jpg	4.5	277653	история,архитектура,природа	Кострома Золотое кольцо Волга
148	Томск	Студенческая столица Сибири с деревянным зодчеством и университетами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/tomsk_1.jpg	4.5	569425	история,архитектура,культура	Томск Сибирь университет
149	Якутск	Самый холодный город мира — столица вечной мерзлоты и алмазного края	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/yakutsk_1.jpg	4.4	369554	природа,экзотика,культура	Якутск мерзлота алмазы
104	Орёл	Литературная столица России — родина Тургенева и Лескова	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/orel_1.jpg	4.3	290000	история,литература,культура	Orel Russia literary city
59	Казань	Город где встречаются две культуры — русская и татарская	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/kazan_1.jpg	4.8	1200000	история,еда,архитектура	Kazan Russia Kremlin Tatarstan
76	Сочи	Черноморский курорт с горами, пляжами и олимпийским наследием	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/sochi_1.jpg	4.7	400000	море,природа,активный	Sochi Russia Black Sea mountains
96	Архангельск	Город у Белого моря — первый морской порт России и ворота в Арктику	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/arkhangelsk_1.jpg	4.3	340000	история,природа,море	Arkhangelsk Russia White Sea Arctic
101	Рязань	Древняя столица с кремлём над Окой и родиной Есенина рядом	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/ryazan_1.jpg	4.4	540000	история,архитектура,природа	Ryazan Russia kremlin Oka
65	Астрахань	Южный форпост России с кремлём у дельты Волги и арбузными бахчами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/astrakhan_2.jpg	4.4	510000	история,природа,еда	Astrakhan Russia Volga delta kremlin
115	Владивосток	Тихоокеанские ворота России с мостами, сопками и морепродуктами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/vladivostok_1.jpg	4.7	600000	море,история,еда	Vladivostok Russia Pacific Ocean bridge
63	Волгоград	Город-герой со скульптурой Родины-матери и великой историей	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/volgograd_1.jpg	4.6	1000000	история,память,архитектура	Volgograd Russia Motherland statue
97	Вологда	Город кружева с белокаменным кремлём и деревянными теремами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/vologda_1.jpg	4.5	310000	история,архитектура,культура	Vologda Russia lace kremlin
98	Калининград	Бывший Кёнигсберг — российский эксклав с немецкими замками и янтарём	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/kaliningrad_1.jpg	4.7	480000	история,архитектура,море	Kaliningrad Russia Germany castle amber
95	Мурманск	Самый большой город за Полярным кругом с полярным сиянием и атомным ледоколом	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/murmansk_1.jpg	4.6	280000	природа,история,активный	Murmansk Russia Arctic northern lights
60	Нижний Новгород	Город на слиянии Волги и Оки с кремлём и купеческими особняками	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/nizhniy_novgorod_1.jpg	4.7	1200000	история,архитектура,еда	Nizhny Novgorod Russia kremlin Volga
78	Ростов-на-Дону	Ворота Кавказа — южный мегаполис на берегу Дона	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/rostov_na_donu_1.jpg	4.4	1100000	история,еда,культура	Rostov-on-Don Russia Don river
110	Уфа	Столица Башкирии с мёдом, кумысом и традициями двух народов	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/ufa_1.jpg	4.3	1100000	история,культура,природа	Ufa Russia Bashkiria city
66	Чебоксары	Столица Чувашии с заливом, набережной и уникальной культурой	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/cheboksary_1.jpg	4.3	490000	история,культура,природа	Cheboksary Russia Volga bay
92	Великий Новгород	Родина российской государственности с кремлём и берестяными грамотами	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/veliky_novgorod_1.jpg	4.7	220000	история,архитектура,религия	Veliky Novgorod Russia kremlin
52	Владимир	Древняя столица с белокаменными соборами под защитой ЮНЕСКО	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/vladimir_1.jpg	4.7	350000	история,архитектура,религия	Vladimir Russia white stone cathedral
31	Иваново	Город невест и ситцевый край — столица текстильной промышленности России	https://raw.githubusercontent.com/KoStRuLyA-1234/travel-images/main/cities/ivanovo_2.jpg	4.3	400000	история,архитектура,шопинг	Ivanovo Russia city
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Email", "PasswordHash", "Name", "HomeCity", "CreatedAt") FROM stdin;
1	Юра@gmail.com	$2a$11$O9Xkyrsi7pJfdQMP93wPeetnRh5mweVDG22OPliQtaiX8STGY8g12	Юра	Иваново	2026-03-20 23:20:11.774698+03
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260317221506_InitialCreate	8.0.0
20260319212237_AddTagsToCity	8.0.0
20260320195941_AddUsers	8.0.0
20260322145629_AddSearchQuery	8.0.0
\.


--
-- Name: Cities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cities_Id_seq"', 149, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: Cities PK_Cities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "PK_Cities" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

\unrestrict WLIuz7nOjQvB2GoX4X4rQBO9V128lRSKLVQijrYwQp93law4hm11WKssqJWYx9e

