-- TravelApp PostgreSQL schema extension.
-- Safe to run on top of the existing database: existing "Users" and "Cities" are preserved.

BEGIN;

ALTER TABLE "Cities"
    ADD COLUMN IF NOT EXISTS "Region" text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "Latitude" double precision,
    ADD COLUMN IF NOT EXISTS "Longitude" double precision,
    ADD COLUMN IF NOT EXISTS "BestSeason" text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "AverageTripDays" integer NOT NULL DEFAULT 2;

ALTER TABLE "Users"
    ADD COLUMN IF NOT EXISTS "Bio" text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "AvatarUrl" text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone;

UPDATE "Users" SET "Email" = lower(trim("Email"));

CREATE TABLE IF NOT EXISTS "Attractions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CityId" integer NOT NULL REFERENCES "Cities"("Id") ON DELETE CASCADE,
    "Name" text NOT NULL,
    "Description" text NOT NULL DEFAULT '',
    "Type" text NOT NULL DEFAULT '',
    "Address" text NOT NULL DEFAULT '',
    "ImageUrl" text NOT NULL DEFAULT '',
    "Latitude" double precision,
    "Longitude" double precision,
    "AverageVisitMinutes" integer NOT NULL DEFAULT 90,
    "PriceLevel" text NOT NULL DEFAULT 'medium',
    "IsFree" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "TravelRoutes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CityId" integer NOT NULL REFERENCES "Cities"("Id") ON DELETE CASCADE,
    "UserId" integer REFERENCES "Users"("Id") ON DELETE SET NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL DEFAULT '',
    "DurationDays" integer NOT NULL DEFAULT 1,
    "Theme" text NOT NULL DEFAULT '',
    "Difficulty" text NOT NULL DEFAULT 'easy',
    "EstimatedBudget" numeric(12,2),
    "IsGenerated" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "RouteStops" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TravelRouteId" integer NOT NULL REFERENCES "TravelRoutes"("Id") ON DELETE CASCADE,
    "AttractionId" integer NOT NULL REFERENCES "Attractions"("Id") ON DELETE CASCADE,
    "DayNumber" integer NOT NULL DEFAULT 1,
    "StopOrder" integer NOT NULL DEFAULT 1,
    "StartTime" text NOT NULL DEFAULT '',
    "DurationMinutes" integer NOT NULL DEFAULT 90,
    "Note" text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "CityId" integer NOT NULL REFERENCES "Cities"("Id") ON DELETE CASCADE,
    "AttractionId" integer REFERENCES "Attractions"("Id") ON DELETE SET NULL,
    "Rating" integer NOT NULL,
    "Text" text NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "CK_Reviews_Rating" CHECK ("Rating" BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS "Favorites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "CityId" integer NOT NULL REFERENCES "Cities"("Id") ON DELETE CASCADE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX IF NOT EXISTS "IX_Cities_Name" ON "Cities" ("Name");
CREATE INDEX IF NOT EXISTS "IX_Cities_Region" ON "Cities" ("Region");
CREATE INDEX IF NOT EXISTS "IX_Attractions_CityId_Type" ON "Attractions" ("CityId", "Type");
CREATE INDEX IF NOT EXISTS "IX_TravelRoutes_CityId" ON "TravelRoutes" ("CityId");
CREATE INDEX IF NOT EXISTS "IX_TravelRoutes_UserId" ON "TravelRoutes" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_RouteStops_AttractionId" ON "RouteStops" ("AttractionId");
CREATE INDEX IF NOT EXISTS "IX_RouteStops_TravelRouteId_DayNumber_StopOrder" ON "RouteStops" ("TravelRouteId", "DayNumber", "StopOrder");
CREATE INDEX IF NOT EXISTS "IX_Reviews_AttractionId" ON "Reviews" ("AttractionId");
CREATE INDEX IF NOT EXISTS "IX_Reviews_CityId_CreatedAt" ON "Reviews" ("CityId", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Reviews_UserId" ON "Reviews" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Favorites_CityId" ON "Favorites" ("CityId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Favorites_UserId_CityId" ON "Favorites" ("UserId", "CityId");

COMMIT;
